# ====================================================================
#  LITH Engine - Configuration File
# ====================================================================
port=8090
public_dir=public
use_cache=1

# Chemins des fichiers d'infrastructure cryptographique (Format PEM)
ssl_cert_path=certs/server.crt
ssl_key_path=certs/server.key

# Doublons de sécurité pour assurer la compatibilité avec load_config
ssl_cert_file=certs/server.crt
ssl_key_file=certs/server.key